services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    init: true
    depends_on:
      - db
    volumes:
      - .:/workspace
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    ports:
      - "8000:8000"
      - "8080:8080"
      - "5173:5173"
      - "8081:8081"

  db:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - laravel_db_data:/var/lib/postgresql

volumes:
  laravel_db_data:
