#!/bin/bash
# tests/ci_report.sh — CI Report Generator
# Generates a human-readable markdown summary of the CI pipeline run.
# Usage: ./tests/ci_report.sh > ci_report.md

set -euo pipefail

COMMIT_SHA="${GITHUB_SHA:-$(git rev-parse --short HEAD 2>/dev/null || echo 'local')}"
BRANCH="${GITHUB_REF_NAME:-$(git branch --show-current 2>/dev/null || echo 'unknown')}"
DATE=$(date -u +"%Y-%m-%d %H:%M UTC")

echo "# Upsilon Battle — CI Report"
echo ""
echo "| Field | Value |"
echo "|---|---|"
echo "| **Date** | $DATE |"
echo "| **Commit** | \`$COMMIT_SHA\` |"
echo "| **Branch** | \`$BRANCH\` |"
echo ""

# --- Go Test Results ---
echo "## Go Unit Tests"
echo ""
GO_RESULTS="go-test-results.json"
if [ -f "$GO_RESULTS" ]; then
    PASS_COUNT=$(grep -c '"Action":"pass"' "$GO_RESULTS" 2>/dev/null || echo "0")
    FAIL_COUNT=$(grep -c '"Action":"fail"' "$GO_RESULTS" 2>/dev/null || echo "0")
    SKIP_COUNT=$(grep -c '"Action":"skip"' "$GO_RESULTS" 2>/dev/null || echo "0")

    if [ "$FAIL_COUNT" -gt 0 ]; then
        echo "| Suite | Passed | Failed | Skipped | Result |"
        echo "|---|---|---|---|---|"
        echo "| Go (all modules) | $PASS_COUNT | $FAIL_COUNT | $SKIP_COUNT | ❌ FAIL |"
        echo ""
        echo "<details><summary>Failed Tests</summary>"
        echo ""
        echo '```'
        grep '"Action":"fail"' "$GO_RESULTS" | head -20
        echo '```'
        echo "</details>"
    else
        echo "| Suite | Passed | Skipped | Result |"
        echo "|---|---|---|---|"
        echo "| Go (all modules) | $PASS_COUNT | $SKIP_COUNT | ✅ PASS |"
    fi
else
    echo "> [!NOTE]"
    echo "> Go test results file not found. Skipped."
fi
echo ""

# --- PHP Test Results ---
echo "## PHP Unit Tests"
echo ""
PHP_RESULTS="php-test-results.txt"
if [ -f "$PHP_RESULTS" ]; then
    if grep -q "FAILED" "$PHP_RESULTS"; then
        echo "| Suite | Result |"
        echo "|---|---|"
        echo "| PHPUnit (battleui) | ❌ FAIL |"
        echo ""
        echo "<details><summary>Output</summary>"
        echo ""
        echo '```'
        tail -20 "$PHP_RESULTS"
        echo '```'
        echo "</details>"
    else
        TESTS_LINE=$(grep -oE "Tests:.*" "$PHP_RESULTS" | tail -1 || echo "Unknown")
        echo "| Suite | Result | Summary |"
        echo "|---|---|---|"
        echo "| PHPUnit (battleui) | ✅ PASS | $TESTS_LINE |"
    fi
else
    echo "> [!NOTE]"
    echo "> PHP test results file not found. Skipped."
fi
echo ""

# --- E2E Battle Results ---
echo "## E2E Battle Scenarios"
echo ""
BATTLE_LOG_DIR="upsiloncli/tests/logs"
if [ -d "$BATTLE_LOG_DIR" ]; then
    echo "| Scenario | Mode | Result |"
    echo "|---|---|---|"
    for logfile in "$BATTLE_LOG_DIR"/*.log; do
        if [ ! -f "$logfile" ]; then continue; fi
        MODE=$(basename "$logfile" .log)
        if grep -q "Game Over! Winner:" "$logfile" || grep -q "STALEMATE" "$logfile"; then
            echo "| Bot Battle | \`$MODE\` | ✅ PASS |"
        else
            echo "| Bot Battle | \`$MODE\` | ❌ FAIL |"
        fi
    done
else
    echo "> [!NOTE]"
    echo "> Battle log directory not found. E2E tests may not have run."
fi
echo ""

# --- BRD Compliance ---
echo "## BRD Compliance Checks"
echo ""
echo "| Requirement | ATD Atom | Script | Status |"
echo "|---|---|---|---|"

# Check if the scripts ran successfully (look for exit code or specific markers)
if [ -f "$BATTLE_LOG_DIR/auth_security.log" ] 2>/dev/null; then
    echo "| Password Policy (BRD 3.1) | \`[[rule_password_policy]]\` | \`auth_security_check.js\` | ✅ |"
else
    echo "| Password Policy (BRD 3.1) | \`[[rule_password_policy]]\` | \`auth_security_check.js\` | ⚠️ No log |"
fi

if [ -f "$BATTLE_LOG_DIR/progression.log" ] 2>/dev/null; then
    echo "| Progression (BRD 2.5) | \`[[rule_progression]]\` | \`progression_check.js\` | ✅ |"
else
    echo "| Progression (BRD 2.5) | \`[[rule_progression]]\` | \`progression_check.js\` | ⚠️ No log |"
fi

echo ""
echo "---"
echo "*Generated by \`tests/ci_report.sh\` at $DATE*"
