#!/bin/bash
# tests/unit_report.sh — Unit Test Report Generator
# Generates a human-readable markdown summary of unit test results.
# Usage: ./tests/unit_report.sh > unit_report.md

set -euo pipefail

COMMIT_SHA="${GITHUB_SHA:-$(git rev-parse --short HEAD 2>/dev/null || echo 'local')}"
DATE=$(date -u +"%Y-%m-%d %H:%M UTC")

echo "# Upsilon — Unit Test Report"
echo ""
echo "| Field | Value |"
echo "|---|---|"
echo "| **Date** | $DATE |"
echo "| **Commit** | \`$COMMIT_SHA\` |"
echo ""

# --- Go Test Results ---
echo "## Go Unit Tests"
echo ""
GO_RESULTS="go-test-results.json"
if [ -f "$GO_RESULTS" ]; then
    PASS_COUNT=$(grep '"Action":"pass"' "$GO_RESULTS" | wc -l)
    FAIL_COUNT=$(grep '"Action":"fail"' "$GO_RESULTS" | wc -l)
    SKIP_COUNT=$(grep '"Action":"skip"' "$GO_RESULTS" | wc -l)

    if [ "$FAIL_COUNT" -gt 0 ]; then
        echo "| Suite | Passed | Failed | Skipped | Result |"
        echo "|---|---|---|---|---|"
        echo "| Go Modules | $PASS_COUNT | $FAIL_COUNT | $SKIP_COUNT | ❌ FAIL |"
        echo ""
        echo "<details><summary>Failed Tests</summary>"
        echo ""
        echo '```'
        grep '"Action":"fail"' "$GO_RESULTS" | head -20
        echo '```'
        echo "</details>"
    else
        echo "| Suite | Passed | Skipped | Result |"
        echo "|---|---|---|---|"
        echo "| Go Modules | $PASS_COUNT | $SKIP_COUNT | ✅ PASS |"
    fi
else
    echo "> [!WARNING]"
    echo "> Go test results file (\`$GO_RESULTS\`) not found."
fi
echo ""

# --- PHP Test Results ---
echo "## PHP Unit Tests"
echo ""
PHP_RESULTS="php-test-results.txt"
if [ -f "$PHP_RESULTS" ]; then
    if grep -q "FAIL" "$PHP_RESULTS"; then
        echo "| Suite | Result |"
        echo "|---|---|"
        echo "| PHPUnit (battleui) | ❌ FAIL |"
        echo ""
        echo "<details><summary>Output</summary>"
        echo ""
        echo '```'
        # Try to find the summary line or just tail
        grep -E "Tests:.*" "$PHP_RESULTS" | tail -1 || true
        echo ""
        tail -20 "$PHP_RESULTS"
        echo '```'
        echo "</details>"
    else
        TESTS_LINE=$(grep -oE "Tests:.*" "$PHP_RESULTS" | tail -1 || echo "Unknown")
        echo "| Suite | Result | Summary |"
        echo "|---|---|---|"
        echo "| PHPUnit (battleui) | ✅ PASS | $TESTS_LINE |"
    fi
else
    echo "> [!WARNING]"
    echo "> PHP test results file (\`$PHP_RESULTS\`) not found."
fi
echo ""
echo "---"
echo "*Generated by \`tests/unit_report.sh\` at $DATE*"
